plugins {
    id 'com.android.application'
}

android {
    namespace 'ch.edelmetall.scanner'
    compileSdk 34

    defaultConfig {
        applicationId 'ch.edelmetall.scanner'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            // Mit dem Debug-Schlüssel signiert, damit die APK direkt installierbar ist.
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
